exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('foods')
    .del()
    .then(function () {
      // Inserts seed entries
      return knex('foods').insert([
        {
          title: 'Powdered milk, skim, instant',
          measurement: '1 1/3 cups',
          grams: 85,
          calories: 290,
          protein: 30,
          total_carbs: 42,
          fibre: 0,
          fat: null,
          saturated_fat: null
        },
        {
          title: 'Powdered milk, skim, non-instant',
          measurement: '2/3 cup',
          grams: 85,
          calories: 290,
          protein: 30,
          total_carbs: 42,
          fibre: 1,
          fat: null,
          saturated_fat: null
        },
        {
          title: "Goats' milk, fresh",
          measurement: '1 cup',
          grams: 244,
          calories: 165,
          protein: 8,
          total_carbs: 11,
          fibre: 0,
          fat: 10,
          saturated_fat: 8
        },
        {
          title: 'Cocoa',
          measurement: '1 cup',
          grams: 252,
          calories: 235,
          protein: 8,
          total_carbs: 26,
          fibre: 0,
          fat: 11,
          saturated_fat: 10
        },
        {
          title: 'Yogurt, of partially skim. Milk',
          measurement: '1 cup',
          grams: 250,
          calories: 128,
          protein: 18,
          total_carbs: 13,
          fibre: 1,
          fat: 4,
          saturated_fat: 3
        },
        {
          title: 'Milk pudding (cornstarch)',
          measurement: '1 cup',
          grams: 248,
          calories: 275,
          protein: 9,
          total_carbs: 40,
          fibre: 0,
          fat: 10,
          saturated_fat: 9
        },
        {
          title: 'Custard, baked',
          measurement: '1 cup',
          grams: 248,
          calories: 285,
          protein: 13,
          total_carbs: 28,
          fibre: 0,
          fat: 14,
          saturated_fat: 11
        },
        {
          title: 'Ice cream, commercial',
          measurement: '1 cup',
          grams: 188,
          calories: 300,
          protein: 6,
          total_carbs: 29,
          fibre: 0,
          fat: 18,
          saturated_fat: 16
        },
        {
          title: 'Ice milk, commercial',
          measurement: '1 cup',
          grams: 190,
          calories: 275,
          protein: 9,
          total_carbs: 32,
          fibre: 0,
          fat: 10,
          saturated_fat: 9
        },
        {
          title: 'Cream, light,or half-and-half',
          measurement: '1/2 cup',
          grams: 120,
          calories: 170,
          protein: 4,
          total_carbs: 5,
          fibre: 0,
          fat: 15,
          saturated_fat: 13
        },
        {
          title: 'Cream, heavy,or whipping',
          measurement: '1/2 cup',
          grams: 119,
          calories: 430,
          protein: 2,
          total_carbs: 3,
          fibre: 1,
          fat: 44,
          saturated_fat: 27
        },
        {
          title: 'Cheese, cottage, creamed',
          measurement: '1 cup',
          grams: 225,
          calories: 240,
          protein: 30,
          total_carbs: 6,
          fibre: 0,
          fat: 11,
          saturated_fat: 10
        },
        {
          title: 'Cheese, cottage uncreamed',
          measurement: '1 cup',
          grams: 225,
          calories: 195,
          protein: 38,
          total_carbs: 6,
          fibre: 0,
          fat: null,
          saturated_fat: null
        },
        {
          title: 'Cheddar, or American',
          measurement: '1-in. cube',
          grams: 17,
          calories: 70,
          protein: 4,
          total_carbs: null,
          fibre: 0,
          fat: 6,
          saturated_fat: 5
        },
        {
          title: 'Cheddar, grated cup',
          measurement: '1/2 cup',
          grams: 56,
          calories: 226,
          protein: 14,
          total_carbs: 1,
          fibre: 0,
          fat: 19,
          saturated_fat: 17
        },
        {
          title: 'Cream cheese',
          measurement: '1 oz.',
          grams: 28,
          calories: 105,
          protein: 2,
          total_carbs: 1,
          fibre: 0,
          fat: 11,
          saturated_fat: 10
        },
        {
          title: 'Processed cheese',
          measurement: '1 oz.',
          grams: 28,
          calories: 105,
          protein: 7,
          total_carbs: null,
          fibre: 0,
          fat: 9,
          saturated_fat: 8
        },
        {
          title: 'Roquefort type',
          measurement: '1 oz.',
          grams: 28,
          calories: 105,
          protein: 6,
          total_carbs: null,
          fibre: 0,
          fat: 9,
          saturated_fat: 8
        },
        {
          title: 'Swiss',
          measurement: '1 oz.',
          grams: 28,
          calories: 105,
          protein: 7,
          total_carbs: null,
          fibre: 0,
          fat: 8,
          saturated_fat: 7
        },
        {
          title: 'Eggs, boiled, poached,or raw',
          measurement: 2,
          grams: 100,
          calories: 150,
          protein: 12,
          total_carbs: null,
          fibre: 0,
          fat: 12,
          saturated_fat: 10
        },
        {
          title: 'or fried',
          measurement: 2,
          grams: 128,
          calories: 220,
          protein: 13,
          total_carbs: 1,
          fibre: 0,
          fat: 16,
          saturated_fat: 14
        },
        {
          title: 'Yolks only',
          measurement: 2,
          grams: 34,
          calories: 120,
          protein: 6,
          total_carbs: null,
          fibre: 0,
          fat: 10,
          saturated_fat: 8
        },
        {
          title: 'Biscuits, 2 1/2" diameters',
          measurement: 1,
          grams: 38,
          calories: 130,
          protein: 3,
          total_carbs: 18,
          fibre: null,
          fat: 4,
          saturated_fat: 3
        },
        {
          title: 'Bran flakes',
          measurement: '1 cup',
          grams: 25,
          calories: 117,
          protein: 3,
          total_carbs: 32,
          fibre: 0.1,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Bread, cracked wheat',
          measurement: '1 slice',
          grams: 23,
          calories: 60,
          protein: 2,
          total_carbs: 12,
          fibre: 0.1,
          fat: 1,
          saturated_fat: 1
        },
        {
          title: 'Bread,  Rye',
          measurement: '1 slice',
          grams: 23,
          calories: 55,
          protein: 2,
          total_carbs: 12,
          fibre: 0.1,
          fat: 1,
          saturated_fat: 1
        },
        {
          title: 'Bread, White, 20 slices, or',
          measurement: '1-lb. loaf',
          grams: 454,
          calories: 1225,
          protein: 39,
          total_carbs: 229,
          fibre: 9,
          fat: 15,
          saturated_fat: 12
        },
        {
          title: 'Bread, Whole-wheat',
          measurement: '1-lb. loaf',
          grams: 454,
          calories: 1100,
          protein: 48,
          total_carbs: 216,
          fibre: 67.5,
          fat: 14,
          saturated_fat: 10
        },
        {
          title: 'Bread, Whole-wheat',
          measurement: '1 slice',
          grams: 23,
          calories: 55,
          protein: 2,
          total_carbs: 11,
          fibre: 0.31,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Corn bread of whole ground meal',
          measurement: '1 serving',
          grams: 50,
          calories: 100,
          protein: 3,
          total_carbs: 15,
          fibre: 0.3,
          fat: 4,
          saturated_fat: 2
        },
        {
          title: 'Cornflakes',
          measurement: '1 cup',
          grams: 25,
          calories: 110,
          protein: 2,
          total_carbs: 25,
          fibre: 0.1,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Corn grits, cooked',
          measurement: '1 cup',
          grams: 242,
          calories: 120,
          protein: 8,
          total_carbs: 27,
          fibre: 0.2,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Corn meal, yellow',
          measurement: '1 cup',
          grams: 118,
          calories: 360,
          protein: 9,
          total_carbs: 74,
          fibre: 1.6,
          fat: 4,
          saturated_fat: 2
        },
        {
          title: 'Crackers, graham',
          measurement: '2 med.',
          grams: 14,
          calories: 55,
          protein: 1,
          total_carbs: 10,
          fibre: null,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Crackers, graham Soda, 2 1/2 square',
          measurement: 2,
          grams: 11,
          calories: 45,
          protein: 1,
          total_carbs: 8,
          fibre: null,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Farina',
          measurement: '1 cup',
          grams: 238,
          calories: 105,
          protein: 3,
          total_carbs: 22,
          fibre: 8,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Flour, soy, full fat',
          measurement: '1 cup',
          grams: 110,
          calories: 460,
          protein: 39,
          total_carbs: 33,
          fibre: 2.9,
          fat: 22,
          saturated_fat: 0
        },
        {
          title: 'Flour wheat (all purpose)',
          measurement: '1 cup',
          grams: 110,
          calories: 400,
          protein: 12,
          total_carbs: 84,
          fibre: 0.3,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Flour Wheat (whole)',
          measurement: '1 cup',
          grams: 120,
          calories: 390,
          protein: 13,
          total_carbs: 79,
          fibre: 2.8,
          fat: 2,
          saturated_fat: 0
        },
        {
          title: 'Macaroni, cooked',
          measurement: '1 cup',
          grams: 140,
          calories: 155,
          protein: 5,
          total_carbs: 32,
          fibre: 0.1,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Macaroni, cooked Baked with cheese',
          measurement: '1 cup',
          grams: 220,
          calories: 475,
          protein: 18,
          total_carbs: 44,
          fibre: null,
          fat: 25,
          saturated_fat: 24
        },
        {
          title: 'Muffins of refined flour',
          measurement: 1,
          grams: 48,
          calories: 135,
          protein: 4,
          total_carbs: 19,
          fibre: null,
          fat: 5,
          saturated_fat: 4
        },
        {
          title: 'Noodles',
          measurement: '1 cup',
          grams: 160,
          calories: 200,
          protein: 7,
          total_carbs: 37,
          fibre: 0.1,
          fat: 2,
          saturated_fat: 2
        },
        {
          title: 'Oatmeal, or rolled oats',
          measurement: '1 cup',
          grams: 236,
          calories: 150,
          protein: 5,
          total_carbs: 26,
          fibre: 4.6,
          fat: 3,
          saturated_fat: 2
        },

        {
          title: 'Pancakes, buckwheat, 4" diam.',
          measurement: 4,
          grams: 108,
          calories: 250,
          protein: 7,
          total_carbs: 28,
          fibre: 0.1,
          fat: 9,
          saturated_fat: 0
        },
        {
          title: 'Pancakes,Wheat, refined flour,4" diam.',
          measurement: 4,
          grams: 108,
          calories: 250,
          protein: 7,
          total_carbs: 28,
          fibre: 0.1,
          fat: 9,
          saturated_fat: 0
        },
        {
          title: 'Pizza, cheese, 1/8 of,14" diam.',
          measurement: '1 section',
          grams: 75,
          calories: 180,
          protein: 8,
          total_carbs: 23,
          fibre: null,
          fat: 6,
          saturated_fat: 5
        },
        {
          title: 'Popcorn, with oil and,salt',
          measurement: '2 cups',
          grams: 28,
          calories: 152,
          protein: 3,
          total_carbs: 20,
          fibre: 0.5,
          fat: 7,
          saturated_fat: 2
        },
        {
          title: 'Puffed rice',
          measurement: '1 cup',
          grams: 14,
          calories: 55,
          protein: null,
          total_carbs: 12,
          fibre: null,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Puffed wheat,presweetened',
          measurement: '1 cup',
          grams: 28,
          calories: 105,
          protein: 1,
          total_carbs: 26,
          fibre: 0.6,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Rice, uncooked, brown',
          measurement: '1 cup',
          grams: 208,
          calories: 748,
          protein: 15,
          total_carbs: 154,
          fibre: 1.2,
          fat: 3,
          saturated_fat: 0
        },
        {
          title: 'Rice, uncooked,Converted',
          measurement: '1 cup',
          grams: 187,
          calories: 677,
          protein: 14,
          total_carbs: 142,
          fibre: 0.4,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Rice, uncooked,White',
          measurement: '1 cup',
          grams: 191,
          calories: 692,
          protein: 14,
          total_carbs: 150,
          fibre: 0.3,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Rice flakes',
          measurement: '1 cup',
          grams: 30,
          calories: 115,
          protein: 2,
          total_carbs: 26,
          fibre: 0.1,
          fat: null,
          saturated_fat: 0
        },
        {
          title: 'Rice polish',
          measurement: '1/2 cup',
          grams: 50,
          calories: 132,
          protein: 6,
          total_carbs: 28,
          fibre: 1.2,
          fat: 6,
          saturated_fat: 0
        },
        {
          title: 'Rolls, breakfast, sweet',
          measurement: '1 large',
          grams: 50,
          calories: 411,
          protein: 3,
          total_carbs: 23,
          fibre: 0.1,
          fat: 12,
          saturated_fat: 11
        },
        {
          title: 'Rolls, breakfast, sweet,of refined flour',
          measurement: 1,
          grams: 38,
          calories: 115,
          protein: 3,
          total_carbs: 20,
          fibre: null,
          fat: 2,
          saturated_fat: 2
        },
        {
          title: 'Rolls, breakfast, sweet,whole-wheat',
          measurement: 1,
          grams: 40,
          calories: 102,
          protein: 4,
          total_carbs: 20,
          fibre: 0.1,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Spaghetti with meat sauce',
          measurement: '1 cup',
          grams: 250,
          calories: 285,
          protein: 13,
          total_carbs: 35,
          fibre: 0.5,
          fat: 10,
          saturated_fat: 6
        },
        {
          title: 'with tomatoes and cheese',
          measurement: '1 cup',
          grams: 250,
          calories: 210,
          protein: 6,
          total_carbs: 36,
          fibre: 0.5,
          fat: 5,
          saturated_fat: 3
        },
        {
          title: 'Spanish rice with meat',
          measurement: '1 cup',
          grams: 250,
          calories: 217,
          protein: 4,
          total_carbs: 40,
          fibre: 1.2,
          fat: 4,
          saturated_fat: 0
        },
        {
          title: 'Shredded wheat biscuit',
          measurement: 1,
          grams: 28,
          calories: 100,
          protein: 3,
          total_carbs: 23,
          fibre: 0.7,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Waffles, 1/2" x 4 1/2" x 5 1/2',
          measurement: 1,
          grams: 75,
          calories: 240,
          protein: 8,
          total_carbs: 30,
          fibre: 0.1,
          fat: 9,
          saturated_fat: 1
        },
        {
          title: 'Wheat germ',
          measurement: '1 cup',
          grams: 68,
          calories: 245,
          protein: 17,
          total_carbs: 34,
          fibre: 2.5,
          fat: 7,
          saturated_fat: 3
        },
        {
          title: 'Wheat-germ cereal,toasted',
          measurement: '1 cup',
          grams: 65,
          calories: 260,
          protein: 20,
          total_carbs: 36,
          fibre: 2.5,
          fat: 7,
          saturated_fat: 3
        },
        {
          title: 'Wheat-meal cereal,unrefined',
          measurement: '3/4 cup',
          grams: 30,
          calories: 103,
          protein: 4,
          total_carbs: 25,
          fibre: 0.7,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Wheat, unground,cooked',
          measurement: '3/4 cup',
          grams: 200,
          calories: 275,
          protein: 12,
          total_carbs: 35,
          fibre: 4.4,
          fat: 1,
          saturated_fat: 0
        },
        {
          title: 'Almonds, dried',
          measurement: '1/2 cup',
          grams: 70,
          calories: 425,
          protein: 13,
          total_carbs: 13,
          fibre: 1.8,
          fat: 38,
          saturated_fat: 28
        },
        {
          title: 'roasted and salted',
          measurement: '1/2 cup',
          grams: 70,
          calories: 439,
          protein: 13,
          total_carbs: 13,
          fibre: 1.8,
          fat: 40,
          saturated_fat: 31
        },
        {
          title: 'Brazil nuts; unsalted',
          measurement: '1/2 cup',
          grams: 70,
          calories: 457,
          protein: 10,
          total_carbs: 7,
          fibre: 2,
          fat: 47,
          saturated_fat: 31
        },
        {
          title: 'Cashews, unsalted',
          measurement: '1/2 cup',
          grams: 70,
          calories: 392,
          protein: 12,
          total_carbs: 20,
          fibre: 0.9,
          fat: 32,
          saturated_fat: 28
        },
        {
          title: 'Coconut, shredded,sweetened',
          measurement: '1/2 cup',
          grams: 50,
          calories: 274,
          protein: 1,
          total_carbs: 26,
          fibre: 2,
          fat: 20,
          saturated_fat: 19
        },
        {
          title: 'Peanut butter, commercial',
          measurement: '1/3 cup',
          grams: 50,
          calories: 300,
          protein: 12,
          total_carbs: 9,
          fibre: 0.9,
          fat: 25,
          saturated_fat: 17
        },
        {
          title: 'Peanut butter, natural',
          measurement: '1/3 cup',
          grams: 50,
          calories: 284,
          protein: 13,
          total_carbs: 8,
          fibre: 0.9,
          fat: 24,
          saturated_fat: 10
        },
        {
          title: 'Peanuts, roasted',
          measurement: '1/3 cup',
          grams: 50,
          calories: 290,
          protein: 13,
          total_carbs: 9,
          fibre: 1.2,
          fat: 25,
          saturated_fat: 16
        },
        {
          title: 'Pecans, raw, halves',
          measurement: '1/2 cup',
          grams: 52,
          calories: 343,
          protein: 5,
          total_carbs: 7,
          fibre: 1.1,
          fat: 35,
          saturated_fat: 25
        },
        {
          title: 'Sesame seeds, dry',
          measurement: '1/2 cup',
          grams: 50,
          calories: 280,
          protein: 9,
          total_carbs: 10,
          fibre: 3.1,
          fat: 24,
          saturated_fat: 13
        },
        {
          title: 'Sunflower seeds',
          measurement: '1/2 cup',
          grams: 50,
          calories: 280,
          protein: 12,
          total_carbs: 10,
          fibre: 1.9,
          fat: 26,
          saturated_fat: 7
        },
        {
          title: 'Walnuts, English, raw',
          measurement: '1/2 cup',
          grams: 50,
          calories: 325,
          protein: 7,
          total_carbs: 8,
          fibre: 1,
          fat: 32,
          saturated_fat: 7
        }
      ]);
    });
};
