export const sampleNutrientData = {
  calories: "218",
  carbs: "6g",
  fat: "3g",
  protein: "31g",
  bad: [
    {
      title: "Calories",
      amount: "218",
      indented: false,
      percentOfDailyNeeds: 10.94,
    },
    { title: "Fat", amount: "3g", indented: false, percentOfDailyNeeds: 5.36 },
    {
      title: "Saturated Fat",
      amount: "0.63g",
      indented: true,
      percentOfDailyNeeds: 3.95,
    },
    {
      title: "Carbohydrates",
      amount: "6g",
      indented: false,
      percentOfDailyNeeds: 2.12,
    },
    { title: "Sugar", amount: "1g", indented: true, percentOfDailyNeeds: 1.76 },
    {
      title: "Cholesterol",
      amount: "370mg",
      indented: false,
      percentOfDailyNeeds: 123.46,
    },
    {
      title: "Sodium",
      amount: "4710mg",
      indented: false,
      percentOfDailyNeeds: 204.79,
    },
    {
      title: "Alcohol",
      amount: "4g",
      indented: false,
      percentOfDailyNeeds: 26.82,
    },
  ],
  good: [
    {
      title: "Protein",
      amount: "31g",
      indented: false,
      percentOfDailyNeeds: 63.22,
    },
    {
      title: "Selenium",
      amount: "81µg",
      indented: false,
      percentOfDailyNeeds: 116.09,
    },
    {
      title: "Vitamin B12",
      amount: "3µg",
      indented: false,
      percentOfDailyNeeds: 57.35,
    },
    {
      title: "Copper",
      amount: "0.9mg",
      indented: false,
      percentOfDailyNeeds: 44.78,
    },
    {
      title: "Manganese",
      amount: "0.88mg",
      indented: false,
      percentOfDailyNeeds: 43.92,
    },
    {
      title: "Zinc",
      amount: "5mg",
      indented: false,
      percentOfDailyNeeds: 35.08,
    },
    {
      title: "Phosphorus",
      amount: "328mg",
      indented: false,
      percentOfDailyNeeds: 32.89,
    },
    {
      title: "Vitamin C",
      amount: "20mg",
      indented: false,
      percentOfDailyNeeds: 24.81,
    },
    {
      title: "Calcium",
      amount: "239mg",
      indented: false,
      percentOfDailyNeeds: 23.94,
    },
    {
      title: "Iron",
      amount: "4mg",
      indented: false,
      percentOfDailyNeeds: 23.83,
    },
    {
      title: "Magnesium",
      amount: "85mg",
      indented: false,
      percentOfDailyNeeds: 21.35,
    },
    {
      title: "Vitamin E",
      amount: "1mg",
      indented: false,
      percentOfDailyNeeds: 12.34,
    },
    {
      title: "Vitamin B5",
      amount: "0.97mg",
      indented: false,
      percentOfDailyNeeds: 9.67,
    },
    {
      title: "Potassium",
      amount: "282mg",
      indented: false,
      percentOfDailyNeeds: 8.08,
    },
    {
      title: "Vitamin B3",
      amount: "1mg",
      indented: false,
      percentOfDailyNeeds: 6.91,
    },
    {
      title: "Vitamin B6",
      amount: "0.14mg",
      indented: false,
      percentOfDailyNeeds: 6.79,
    },
    {
      title: "Folate",
      amount: "23µg",
      indented: false,
      percentOfDailyNeeds: 5.86,
    },
    {
      title: "Vitamin B2",
      amount: "0.1mg",
      indented: false,
      percentOfDailyNeeds: 5.59,
    },
    {
      title: "Vitamin A",
      amount: "234IU",
      indented: false,
      percentOfDailyNeeds: 4.69,
    },
    {
      title: "Fiber",
      amount: "1g",
      indented: false,
      percentOfDailyNeeds: 4.36,
    },
    {
      title: "Vitamin B1",
      amount: "0.05mg",
      indented: false,
      percentOfDailyNeeds: 3.38,
    },
    {
      title: "Vitamin D",
      amount: "0.21µg",
      indented: false,
      percentOfDailyNeeds: 1.37,
    },
  ],
  expires: 1568888275683,
  isStale: true,
};
