export const sampleRecipies = [
  {
    id: 76342,
    title: "Fruits De Mer Platter",
    image: "https://spoonacular.com/recipeImages/76342-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 218.731, unit: "cal" },
      { title: "Protein", amount: 31.6121, unit: "g" },
      { title: "Fat", amount: 3.48582, unit: "g" },
      { title: "Carbohydrates", amount: 6.35438, unit: "g" },
    ],
  },
  {
    id: 564767,
    title: "Dry Fruits Milkshake | Iron Rich s",
    image: "https://spoonacular.com/recipeImages/564767-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 368.664, unit: "cal" },
      { title: "Protein", amount: 10.3878, unit: "g" },
      { title: "Fat", amount: 3.02453, unit: "g" },
      { title: "Carbohydrates", amount: 80.9905, unit: "g" },
    ],
  },
  {
    id: 488019,
    title: "dry fruits ladoo or dry fruits laddu, how to make dry fruits ladoo",
    image: "https://spoonacular.com/recipeImages/488019-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 507.54, unit: "cal" },
      { title: "Protein", amount: 7.09895, unit: "g" },
      { title: "Fat", amount: 9.8494, unit: "g" },
      { title: "Carbohydrates", amount: 110.915, unit: "g" },
    ],
  },
  {
    id: 214071,
    title: "Dried fruits in cognac",
    image: "https://spoonacular.com/recipeImages/214071-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 174.561, unit: "cal" },
      { title: "Protein", amount: 0.520413, unit: "g" },
      { title: "Fat", amount: 0.11085, unit: "g" },
      { title: "Carbohydrates", amount: 36.1993, unit: "g" },
    ],
  },
  {
    id: 542277,
    title: "Fresh Fruits and Ricotta Phyllo Cups",
    image: "https://spoonacular.com/recipeImages/542277-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 136.283, unit: "cal" },
      { title: "Protein", amount: 4.80811, unit: "g" },
      { title: "Fat", amount: 1.09101, unit: "g" },
      { title: "Carbohydrates", amount: 27.4577, unit: "g" },
    ],
  },
  {
    id: 1162674,
    title: "Dried Fruits in Oven Using Dehydrate Setting",
    image: "https://spoonacular.com/recipeImages/1162674-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 68.86, unit: "cal" },
      { title: "Protein", amount: 1.2873, unit: "g" },
      { title: "Fat", amount: 0.393325, unit: "g" },
      { title: "Carbohydrates", amount: 17.0682, unit: "g" },
    ],
  },
  {
    id: 142705,
    title: "Stone Fruits with Honey-Drizzled Soft Cheeses and Toasted Almonds",
    image: "https://spoonacular.com/recipeImages/142705-312x231.png",
    imageType: "png",
    nutrition: [
      { title: "Calories", amount: 345.783, unit: "cal" },
      { title: "Protein", amount: 12.3313, unit: "g" },
      { title: "Fat", amount: 24.9806, unit: "g" },
      { title: "Carbohydrates", amount: 21.1393, unit: "g" },
    ],
  },
  {
    id: 127635,
    title: "Summer Fruits With Tahini Ganache",
    image: "https://spoonacular.com/recipeImages/127635-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 478.97, unit: "cal" },
      { title: "Protein", amount: 6.72881, unit: "g" },
      { title: "Fat", amount: 32.1344, unit: "g" },
      { title: "Carbohydrates", amount: 44.9918, unit: "g" },
    ],
  },
  {
    id: 125835,
    title: "Summer Fruits Terrine or Bodacious Berries in Wine Jelly!",
    image: "https://spoonacular.com/recipeImages/125835-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 116.14, unit: "cal" },
      { title: "Protein", amount: 2.78386, unit: "g" },
      { title: "Fat", amount: 0.489278, unit: "g" },
      { title: "Carbohydrates", amount: 21.0835, unit: "g" },
    ],
  },
  {
    id: 752690,
    title: "Roasted Fruits with Cinnamon-Red Wine Glaze and Toasted Almonds",
    image: "https://spoonacular.com/recipeImages/752690-312x231.jpeg",
    imageType: "jpeg",
    nutrition: [
      { title: "Calories", amount: 484.946, unit: "cal" },
      { title: "Protein", amount: 10.5022, unit: "g" },
      { title: "Fat", amount: 18.2298, unit: "g" },
      { title: "Carbohydrates", amount: 77.0412, unit: "g" },
    ],
  },
  {
    id: 220381,
    title: "Tropical fruits in lemongrass syrup",
    image: "https://spoonacular.com/recipeImages/220381-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 358.533, unit: "cal" },
      { title: "Protein", amount: 2.94375, unit: "g" },
      { title: "Fat", amount: 15.567, unit: "g" },
      { title: "Carbohydrates", amount: 57.8718, unit: "g" },
    ],
  },
  {
    id: 1016859,
    title: "Tropical Fruits Cheesecake Crumb Cake",
    image: "https://spoonacular.com/recipeImages/1016859-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 508.159, unit: "cal" },
      { title: "Protein", amount: 8.22875, unit: "g" },
      { title: "Fat", amount: 26.3857, unit: "g" },
      { title: "Carbohydrates", amount: 60.905, unit: "g" },
    ],
  },
  {
    id: 697978,
    title: "Tropical Fruits with Pistachios & Coconut",
    image: "https://spoonacular.com/recipeImages/697978-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 27.5823, unit: "cal" },
      { title: "Protein", amount: 0.792925, unit: "g" },
      { title: "Fat", amount: 2.0456, unit: "g" },
      { title: "Carbohydrates", amount: 1.79496, unit: "g" },
    ],
  },
  {
    id: 615372,
    title: "Nuts and Fruits Energy Bars {Homemade Kind Bars}",
    image: "https://spoonacular.com/recipeImages/615372-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 149.761, unit: "cal" },
      { title: "Protein", amount: 3.49673, unit: "g" },
      { title: "Fat", amount: 7.55448, unit: "g" },
      { title: "Carbohydrates", amount: 19.3079, unit: "g" },
    ],
  },
  {
    id: 528128,
    title: "Preserve Fruits and Vegetables & Tomato Cucumber Salad",
    image: "https://spoonacular.com/recipeImages/528128-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 428.91, unit: "cal" },
      { title: "Protein", amount: 8.3782, unit: "g" },
      { title: "Fat", amount: 30.2764, unit: "g" },
      { title: "Carbohydrates", amount: 39.5042, unit: "g" },
    ],
  },
  {
    id: 770052,
    title: "Sparkling Fruits Party Punch",
    image: "https://spoonacular.com/recipeImages/770052-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 119.877, unit: "cal" },
      { title: "Protein", amount: 0.216553, unit: "g" },
      { title: "Fat", amount: 0.127021, unit: "g" },
      { title: "Carbohydrates", amount: 30.1558, unit: "g" },
    ],
  },
  {
    id: 232248,
    title: "Caribbean Fruits With Key Lime Dip",
    image: "https://spoonacular.com/recipeImages/232248-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 289.374, unit: "cal" },
      { title: "Protein", amount: 4.66486, unit: "g" },
      { title: "Fat", amount: 19.9607, unit: "g" },
      { title: "Carbohydrates", amount: 26.3732, unit: "g" },
    ],
  },
  {
    id: 703206,
    title: "Grey Goose Fruits de Fête Champagne Cocktail",
    image: "https://spoonacular.com/recipeImages/703206-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 231.503, unit: "cal" },
      { title: "Protein", amount: 0.465528, unit: "g" },
      { title: "Fat", amount: 0.0991184, unit: "g" },
      { title: "Carbohydrates", amount: 9.07787, unit: "g" },
    ],
  },
  {
    id: 57844,
    title: "Eating more fruits and vegetables at the Dole Blogger Summit",
    image: "https://spoonacular.com/recipeImages/57844-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 159.586, unit: "cal" },
      { title: "Protein", amount: 2.40151, unit: "g" },
      { title: "Fat", amount: 4.25885, unit: "g" },
      { title: "Carbohydrates", amount: 31.0053, unit: "g" },
    ],
  },
  {
    id: 49027,
    title: "Sliced Stone Fruits With Muscat Sabayon",
    image: "https://spoonacular.com/recipeImages/49027-312x231.jpg",
    imageType: "jpg",
    nutrition: [
      { title: "Calories", amount: 123.745, unit: "cal" },
      { title: "Protein", amount: 3.35215, unit: "g" },
      { title: "Fat", amount: 4.70445, unit: "g" },
      { title: "Carbohydrates", amount: 15.6586, unit: "g" },
    ],
  },
];
